//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aLice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aLice.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LangUtil_Yes {
            get {
                return ResourceManager.GetString("LangUtil_Yes", resourceCulture);
            }
        }
        
        internal static string LangUtil_No {
            get {
                return ResourceManager.GetString("LangUtil_No", resourceCulture);
            }
        }
        
        internal static string LangUtil_Close {
            get {
                return ResourceManager.GetString("LangUtil_Close", resourceCulture);
            }
        }
        
        internal static string LangUtil_AddressCopy {
            get {
                return ResourceManager.GetString("LangUtil_AddressCopy", resourceCulture);
            }
        }
        
        internal static string LangUtil_PublicKeyCopy {
            get {
                return ResourceManager.GetString("LangUtil_PublicKeyCopy", resourceCulture);
            }
        }
        
        internal static string LangUtil_PrivateKeyCopy {
            get {
                return ResourceManager.GetString("LangUtil_PrivateKeyCopy", resourceCulture);
            }
        }
        
        internal static string LangUtil_Biometrics {
            get {
                return ResourceManager.GetString("LangUtil_Biometrics", resourceCulture);
            }
        }
        
        internal static string LangUtil_Delete {
            get {
                return ResourceManager.GetString("LangUtil_Delete", resourceCulture);
            }
        }
        
        internal static string LangUtil_InputPassword {
            get {
                return ResourceManager.GetString("LangUtil_InputPassword", resourceCulture);
            }
        }
        
        internal static string LangUtil_FailedPassword {
            get {
                return ResourceManager.GetString("LangUtil_FailedPassword", resourceCulture);
            }
        }
        
        internal static string LangUtil_CopiedToClipBoard {
            get {
                return ResourceManager.GetString("LangUtil_CopiedToClipBoard", resourceCulture);
            }
        }
        
        internal static string LangUtil_IncorrectNetwork {
            get {
                return ResourceManager.GetString("LangUtil_IncorrectNetwork", resourceCulture);
            }
        }
        
        internal static string BarcodeReader_GetPrivateKey_Discription {
            get {
                return ResourceManager.GetString("BarcodeReader_GetPrivateKey_Discription", resourceCulture);
            }
        }
        
        internal static string App_NoAccount {
            get {
                return ResourceManager.GetString("App_NoAccount", resourceCulture);
            }
        }
        
        internal static string App_NotificationError {
            get {
                return ResourceManager.GetString("App_NotificationError", resourceCulture);
            }
        }
        
        internal static string App_RegisterDomain {
            get {
                return ResourceManager.GetString("App_RegisterDomain", resourceCulture);
            }
        }
        
        internal static string Account_OnClickSubmitAccount_DialigTitle {
            get {
                return ResourceManager.GetString("Account_OnClickSubmitAccount_DialigTitle", resourceCulture);
            }
        }
        
        internal static string Account_OnClickSubmitAccount_Success {
            get {
                return ResourceManager.GetString("Account_OnClickSubmitAccount_Success", resourceCulture);
            }
        }
        
        internal static string MainPage_SettingMainAccount {
            get {
                return ResourceManager.GetString("MainPage_SettingMainAccount", resourceCulture);
            }
        }
        
        internal static string MainPage_ChangedAccount {
            get {
                return ResourceManager.GetString("MainPage_ChangedAccount", resourceCulture);
            }
        }
        
        internal static string MainPage_CopiedAddressToClipBoard {
            get {
                return ResourceManager.GetString("MainPage_CopiedAddressToClipBoard", resourceCulture);
            }
        }
        
        internal static string MainPage_CopiedPublicKeyToClipBoard {
            get {
                return ResourceManager.GetString("MainPage_CopiedPublicKeyToClipBoard", resourceCulture);
            }
        }
        
        internal static string MainPage_CopiedPrivateKeyToClipBoard {
            get {
                return ResourceManager.GetString("MainPage_CopiedPrivateKeyToClipBoard", resourceCulture);
            }
        }
        
        internal static string MainPage_WarningPrivateKey {
            get {
                return ResourceManager.GetString("MainPage_WarningPrivateKey", resourceCulture);
            }
        }
        
        internal static string MainPage_ConfirmDeleteAccount {
            get {
                return ResourceManager.GetString("MainPage_ConfirmDeleteAccount", resourceCulture);
            }
        }
        
        internal static string MainPage_DeletedAccount {
            get {
                return ResourceManager.GetString("MainPage_DeletedAccount", resourceCulture);
            }
        }
        
        internal static string MainPage_ConfirmActivateBionic {
            get {
                return ResourceManager.GetString("MainPage_ConfirmActivateBionic", resourceCulture);
            }
        }
        
        internal static string MainPage_ConfirmDeactivateBionic {
            get {
                return ResourceManager.GetString("MainPage_ConfirmDeactivateBionic", resourceCulture);
            }
        }
        
        internal static string MainPage_ActivatedBionic {
            get {
                return ResourceManager.GetString("MainPage_ActivatedBionic", resourceCulture);
            }
        }
        
        internal static string MainPage_DeactivatedBionic {
            get {
                return ResourceManager.GetString("MainPage_DeactivatedBionic", resourceCulture);
            }
        }
        
        internal static string RequestGetPubKey_Confirm {
            get {
                return ResourceManager.GetString("RequestGetPubKey_Confirm", resourceCulture);
            }
        }
        
        internal static string RequestGetPubKey_AccountSwitching {
            get {
                return ResourceManager.GetString("RequestGetPubKey_AccountSwitching", resourceCulture);
            }
        }
        
        internal static string RequestSign_ConfirmChangeAccount {
            get {
                return ResourceManager.GetString("RequestSign_ConfirmChangeAccount", resourceCulture);
            }
        }
        
        internal static string RequestSign_ConfirmChangeAccountDescription {
            get {
                return ResourceManager.GetString("RequestSign_ConfirmChangeAccountDescription", resourceCulture);
            }
        }
        
        internal static string RequestSign_ConfirmSign {
            get {
                return ResourceManager.GetString("RequestSign_ConfirmSign", resourceCulture);
            }
        }
        
        internal static string Settings_PasswordStorageTime {
            get {
                return ResourceManager.GetString("Settings_PasswordStorageTime", resourceCulture);
            }
        }
        
        internal static string Settings_PasswordStorageTimeDiscription {
            get {
                return ResourceManager.GetString("Settings_PasswordStorageTimeDiscription", resourceCulture);
            }
        }
        
        internal static string WaitConfirmed_SuccessTransaction {
            get {
                return ResourceManager.GetString("WaitConfirmed_SuccessTransaction", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_FailedBionic {
            get {
                return ResourceManager.GetString("AccountViewModel_FailedBionic", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_RequiredAccountName {
            get {
                return ResourceManager.GetString("AccountViewModel_RequiredAccountName", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_RequiredPassword {
            get {
                return ResourceManager.GetString("AccountViewModel_RequiredPassword", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_RequiredAddress {
            get {
                return ResourceManager.GetString("AccountViewModel_RequiredAddress", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_RequiredPrivateKey {
            get {
                return ResourceManager.GetString("AccountViewModel_RequiredPrivateKey", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_NotMatchPrivateKeyAndAddress {
            get {
                return ResourceManager.GetString("AccountViewModel_NotMatchPrivateKeyAndAddress", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_AccountAlreadyRegistered {
            get {
                return ResourceManager.GetString("AccountViewModel_AccountAlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string AccountViewModel_AddressAlreadyRegistered {
            get {
                return ResourceManager.GetString("AccountViewModel_AddressAlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_RequestSignature {
            get {
                return ResourceManager.GetString("RequestViewModel_RequestSignature", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_Utf8String {
            get {
                return ResourceManager.GetString("RequestViewModel_Utf8String", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_Hex {
            get {
                return ResourceManager.GetString("RequestViewModel_Hex", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_Cosignature {
            get {
                return ResourceManager.GetString("RequestViewModel_Cosignature", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_SymbolTransaction {
            get {
                return ResourceManager.GetString("RequestViewModel_SymbolTransaction", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_EncryptionMessage {
            get {
                return ResourceManager.GetString("RequestViewModel_EncryptionMessage", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_MultipleTransactions {
            get {
                return ResourceManager.GetString("RequestViewModel_MultipleTransactions", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_IncorrectRequest {
            get {
                return ResourceManager.GetString("RequestViewModel_IncorrectRequest", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_IncorrectNodeUrl {
            get {
                return ResourceManager.GetString("RequestViewModel_IncorrectNodeUrl", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_FailedAnnounce {
            get {
                return ResourceManager.GetString("RequestViewModel_FailedAnnounce", resourceCulture);
            }
        }
        
        internal static string RequestViewModel_NoAccount {
            get {
                return ResourceManager.GetString("RequestViewModel_NoAccount", resourceCulture);
            }
        }
        
        internal static string SymbolTranasction_NoPublicKey {
            get {
                return ResourceManager.GetString("SymbolTranasction_NoPublicKey", resourceCulture);
            }
        }
        
        internal static string SymbolTranasction_NoEpocTime {
            get {
                return ResourceManager.GetString("SymbolTranasction_NoEpocTime", resourceCulture);
            }
        }
    }
}
